Solution
mate-academy/js_format_date_advanced pull request #1678
Opened 2023-11-25 12:30 UTC by KaterynaEV

2023-11-25 14:14 UTC, VitaliyBodnar requested changes

2023-11-25 14:14 UTC, VitaliyBodnar commented on src/formatDate.js
> +    }
- please use switch case statement instead of multiple if blocks 
- YYYY, MM, DD are magic words, so it's make sense to move them to constant

2023-11-25 14:14 UTC, VitaliyBodnar commented on src/formatDate.js
> +          formated.push(19 + year);
4, 19, 20 and 30 are the magic numbers, so make sense to move the to the constants

2023-11-25 14:14 UTC, VitaliyBodnar commented on src/formatDate.js
> +        }
make sense to use ternary operator here as it will make a code shorter

2023-11-25 14:15 UTC, VitaliyBodnar requested changes
.

2023-11-27 12:28 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2023-11-27 12:28 UTC, anastasiiavorobiova commented on src/formatDate.js
> +      case 'YY':
Consider using variables with meaningful names instead of magic strings

2023-11-27 12:28 UTC, anastasiiavorobiova commented on src/formatDate.js
> +      case 'MM':
The same issue here

2023-11-27 12:28 UTC, anastasiiavorobiova commented on src/formatDate.js
> +      case 'DD':
Also, could you please fix this further in the code?

2023-12-13 16:59 UTC, Esceype requested changes

2023-12-13 16:59 UTC, Esceype commented on src/formatDate.js
> +        case 'YYYY':
Move `YYYY` and `YY` to variable please, it still not fixed from previous comments

2023-12-14 09:21 UTC, closed without merging