task done, all tests passed
mate-academy/js_format_date_advanced pull request #1710
Opened 2023-12-12 14:15 UTC by Manankin

Done !

2023-12-14 21:51 UTC, vSainiuk commented on src/formatDate.js
> +  const NEW_DIVIDER = toFormat[3];
I think it is better to name the variable like 'separator' for better understanding)

2023-12-14 21:54 UTC, vSainiuk approved these changes
I like it. Well done!

2023-12-15 08:01 UTC, DanilWeda requested changes
Thanks for a good job! 
Check comments for improvement!

2023-12-15 08:01 UTC, DanilWeda commented on src/formatDate.js
> +        result.push(number);
Use a function for all case results.

2023-12-15 13:36 UTC, olya-shyian requested changes
Great! You did a nice job!)

2023-12-15 13:36 UTC, olya-shyian commented on src/formatDate.js
> +      number = number >= 30 ? '19' + number : '20' + number;
99, 30 , 19, 20 what do these magic numbers mean?
could you use variables for them?

2023-12-15 14:28 UTC, olya-shyian approved these changes
Excellent!🤩

2024-09-19 12:26 UTC, closed without merging