Js format date advanced HW
mate-academy/js_format_date_advanced pull request #481
Opened 2022-02-14 13:07 UTC by Ostafii4uk

2022-02-14 14:52 UTC, barannikovArtem requested changes
GJ. little fixes.

2022-02-14 14:52 UTC, barannikovArtem commented on src/formatDate.js
> +  for (let i = 0; i < 3; i++) {
what is 3?

2022-02-14 14:52 UTC, barannikovArtem commented on src/formatDate.js
> +      if (objFormatData['YY'] >= 30) {
what is 30?

2022-02-14 16:49 UTC, Ostafii4uk commented on src/formatDate.js
> +      if (objFormatData['YY'] >= 30) {
too)

2022-02-15 10:57 UTC, solaryasha requested changes

2022-02-15 10:57 UTC, solaryasha commented on src/formatDate.js
> +  const objFormatData = {};
https://mateacademy.slack.com/archives/C02T596SHUZ/p1644920876764629

2022-02-15 10:57 UTC, solaryasha commented on src/formatDate.js
> +  const arrToFormat = [];
https://mateacademy.slack.com/archives/C02T596SHUZ/p1644920876764629

2022-02-15 10:57 UTC, solaryasha commented on src/formatDate.js
> +      }
Це форматування можеш винести в окрему функцію

2022-02-15 13:35 UTC, Ostafii4uk commented on src/formatDate.js
> +      }
done

2022-02-15 13:53 UTC, solaryasha approved these changes

2022-02-15 13:53 UTC, solaryasha commented on src/formatDate.js
> +  }
Винеси цю функцію з функції `formatDate`

2022-02-15 13:53 UTC, solaryasha commented on src/formatDate.js
> +  const splitData = date.split(fromFormat[3]);
```suggestion
  const splitedDate = date.split(fromFormat[3]);
```

2022-02-15 14:51 UTC, closed without merging