Solution
mate-academy/js_format_date_advanced pull request #674
Opened 2022-07-11 21:15 UTC by blcts

2022-07-11 21:44 UTC, chernobrovin requested changes
Your solution is perfect, but you need to fix your variable's names

2022-07-11 21:44 UTC, chernobrovin commented on src/formatDate.js
> +  const newdate = date.split(`${fromFormat[fromFormat.length - 1]}`);
you shood use 'camel case'
```suggestion
  const newDate = date.split(`${fromFormat[fromFormat.length - 1]}`);
```

2022-07-12 08:40 UTC, chernobrovin approved these changes
Perfect!

2022-07-12 09:22 UTC, Ihor-Karpyn approved these changes

2023-04-19 13:47 UTC, closed without merging