formatDate Solution
mate-academy/js_format_date_advanced pull request #769
Opened 2022-09-08 13:21 UTC by mykola-chernysh

2022-09-09 17:19 UTC, SanyaBratashchuk requested changes

2022-09-09 17:19 UTC, SanyaBratashchuk commented on src/formatDate.js
> +  }
В якому випадку цей else спрацює?

2022-09-17 07:23 UTC, mykola-chernysh commented on src/formatDate.js
> +  }
Коли dateObject.YY === undefined

2022-09-22 17:19 UTC, TarasHoliuk approved these changes
Approved

2023-11-27 07:09 UTC, closed without merging