js_format_date_advanced
mate-academy/js_format_date_advanced pull request #798
Opened 2022-09-16 12:42 UTC by xiimiik

2022-09-16 14:13 UTC, Dikey945 commented
Good Job! Keep going 🚀

2022-09-19 11:08 UTC, OleksiiBlezniuk requested changes

2022-09-19 11:08 UTC, OleksiiBlezniuk commented on src/formatDate.js
> +      }
Move this logic to separated function

2022-09-19 11:08 UTC, OleksiiBlezniuk commented on src/formatDate.js
> +    if (!dateObj.hasOwnProperty(toFormat[i])) {
It's strange that you have to overwrite element in array after adding, you can wrap `push` in `if` and break loop after element adding. Then there will be no need to wrap other logic of loop in `if` and you'll be able to push modified year to array

2022-09-20 09:03 UTC, OleksiiBlezniuk approved these changes

2022-09-20 09:03 UTC, OleksiiBlezniuk commented on src/formatDate.js
> +function formatedYear(year) {
```suggestion
function formatYear(year) {
```

2022-09-20 09:03 UTC, OleksiiBlezniuk commented on src/formatDate.js
> +function formatedYear(year) {
format - action, formatted - result of this action

2025-09-02 10:19 UTC, closed without merging