Solution
mate-academy/js_format_date_advanced pull request #932
Opened 2022-11-29 09:40 UTC by vlad-boikov

feels like a shitcode))))

2022-11-30 09:42 UTC, Bohdan-Maksymiuk requested changes
You can create object 


const dateObj = {
	DD: '',
	MM: '',
	YY: '',
	YYYY: '',
  };

2022-11-30 09:42 UTC, Bohdan-Maksymiuk commented on src/formatDate.js
> +  }
ohh, try to avoid such nested loops
it increases time complexity of your code

2022-12-01 09:15 UTC, Virass approved these changes

2022-12-01 09:15 UTC, Bohdan-Maksymiuk requested changes

2022-12-01 09:15 UTC, Bohdan-Maksymiuk commented on src/formatDate.js
> +    }
try to avoid `else if`
end lets remove such check from the loop

2022-12-01 09:15 UTC, Bohdan-Maksymiuk commented on src/formatDate.js
> +    }
you may leave in the loop only
`dateObj[fromFormat[i]] = splitted[i];`

2022-12-01 09:15 UTC, Bohdan-Maksymiuk commented on src/formatDate.js
> +    }
after it you can calculate `dateObj.YYYY` and `dateObj.YY`

2022-12-01 19:38 UTC, AlisaVlasova approved these changes

2025-02-27 17:26 UTC, closed without merging